# Tests
DIR_TEST_ITEMS := csdetect:csdetect.c dict:dict.c entities:entities.c \
	hubbub:hubbub.c parser:parser.c tokeniser:tokeniser.c \
	tokeniser2:tokeniser2.c tokeniser3:tokeniser3.c tree:tree.c \
	tree2:tree2.c tree-buf:tree-buf.c

include build/makefiles/Makefile.subdir
